---
title: configure-context-menu
description: configure context menu
privilege: TrustedInstaller
actions:

  # - add `Windows Batch File`, `Hash`, `Registry Entries`, `Windows Powershell Script`. in context menu
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\.bat\\ShellNew', value: '\"NullFile\"', type: REG_SZ, data: '\"\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash', value: '\"MUIVerb\"', type: REG_SZ, data: '\"Hash\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash', value: '\"SubCommands\"', type: REG_SZ, data: '\"\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\01menu', value: '\"MUIVerb\"', type: REG_SZ, data: '\"SHA1\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\01menu\\command', value: '@', type: REG_SZ, data: '\"powershell -noexit get-filehash -literalpath '%%1' -algorithm SHA1 | format-list\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\02menu', value: '\"MUIVerb\"', type: REG_SZ, data: '\"SHA256\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\02menu\\command', value: '@', type: REG_SZ, data: '\"powershell -noexit get-filehash -literalpath '%%1' -algorithm SHA256 | format-list\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\03menu', value: '\"MUIVerb\"', type: REG_SZ, data: '\"SHA384\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\03menu\\command', value: '@', type: REG_SZ, data: '\"powershell -noexit get-filehash -literalpath '%%1' -algorithm SHA384 | format-list\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\04menu', value: '\"MUIVerb\"', type: REG_SZ, data: '\"SHA512\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\04menu\\command', value: '@', type: REG_SZ, data: '\"powershell -noexit get-filehash -literalpath '%%1' -algorithm SHA512 | format-list\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\05menu', value: '\"MUIVerb\"', type: REG_SZ, data: '\"MACTripleDES\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\05menu\\command', value: '@', type: REG_SZ, data: '\"powershell -noexit get-filehash -literalpath '%%1' -algorithm MACTripleDES | format-list\"'}
  #- !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\06menu', value: '\"MUIVerb\"', type: REG_SZ, data: '\"MD5\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\06menu\\command', value: '@', type: REG_SZ, data: '\"powershell -noexit get-filehash -literalpath '%%1' -algorithm MD5 | format-list\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\07menu', value: '\"MUIVerb\"', type: REG_SZ, data: '\"RIPEMD160\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\07menu\\command', value: '@', type: REG_SZ, data: '\"powershell -noexit get-filehash -literalpath '%%1' -algorithm RIPEMD160 | format-list\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\08menu', value: '\"CommandFlags\"', type: REG_DWORD, data: '00000020'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\08menu', value: '\"MUIVerb\"', type: REG_SZ, data: '\"Show all\"'}
  #- !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\*\\shell\\hash\\shell\\08menu\\command', value: '@', type: REG_SZ, data: '\"powershell -noexit get-filehash -literalpath '%%1' -algorithm SHA1 | format-list;get-filehash -literalpath '%%1' -algorithm SHA256 | format-list;get-filehash -literalpath '%%1' -algorithm SHA384 | format-list;get-filehash -literalpath '%%1' -algorithm SHA512 | format-list;get-filehash -literalpath '%%1' -algorithm MACTripleDES | format-list;get-filehash -literalpath '%%1' -algorithm MD5 | format-list;get-filehash -literalpath '%%1' -algorithm RIPEMD160 | format-list\"'}
#  - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\.reg\\ShellNew', value: '\"ItemName\"', type: REG_SZ, data: 'hex(2):40,00,25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,\\'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\.reg\\ShellNew', value: '\"NullFile\"', type: REG_SZ, data: '\"\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\.ps1', value: '@', type: REG_SZ, data: '\"ps1legacy\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\.ps1\\ShellNew', value: '\"NullFile\"', type: REG_SZ, data: '\"\"'}
  #- !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\ps1legacy', value: '@', type: REG_SZ, data: '\"Windows PowerShell Script\"'}
  #- !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\ps1legacy', value: '\"FriendlyTypeName\"', type: REG_SZ, data: '\"Windows PowerShell Script\"'}

  # - Command Prompt in directory shit + right-click context menu
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\Directory\\shell\\cmd2', value: '@', type: REG_SZ, data: '\"@shell32.dll,-8506\"'}
#  - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\Directory\\shell\\cmd2', value: '\"Extended\"', type: REG_SZ, data: '\"\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\Directory\\shell\\cmd2', value: '\"Icon\"', type: REG_SZ, data: '\"imageres.dll,-5323\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\Directory\\shell\\cmd2', value: '\"NoWorkingDirectory\"', type: REG_SZ, data: '\"\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\Directory\\shell\\cmd2\\command', value: '@', type: REG_SZ, data: '\"cmd.exe /s /k pushd \\\"%V\\\"\"'}
  #- !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\Directory\\Background\\shell\\cmd2', value: '@', type: REG_SZ, data: '\"@shell32.dll,-8506\"'}
#  - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\Directory\\Background\\shell\\cmd2', value: '\"Extended\"', type: REG_SZ, data: '\"\"'}
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\Directory\\Background\\shell\\cmd2', value: '\"Icon\"', type: REG_SZ, data: '\"imageres.dll,-5323\"'}
#  - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\Directory\\Background\\shell\\cmd2', value: '\"NoWorkingDirectory\"', type: REG_SZ, data: '\"\"'}
#  - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\Directory\\Background\\shell\\cmd2\\command', value: '@', type: REG_SZ, data: '\"cmd.exe /s /k pushd \\\"%V\\\"\"'}
#  - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\Drive\\shell\\cmd2', value: '@', type: REG_SZ, data: '\"@shell32.dll,-8506\"'}
#  - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\Drive\\shell\\cmd2', value: '\"Extended\"', type: REG_SZ, data: '\"\"'}
#  - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\Drive\\shell\\cmd2', value: '\"Icon\"', type: REG_SZ, data: '\"imageres.dll,-5323\"'}
#  - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\Drive\\shell\\cmd2', value: '\"NoWorkingDirectory\"', type: REG_SZ, data: '\"\"'}
#  - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\Drive\\shell\\cmd2\\command', value: '@', type: REG_SZ, data: '\"cmd.exe /s /k pushd \\\"%V\\\"\"'}

  # - remove network in explorer
 # - !registryValue: {path: 'HKLM\\SOFTWARE\\Classes\\CLSID\\{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}\\ShellFolder', value: '\"Attributes\"', type: REG_DWORD, data: 'b0940064'}

  # - Remove previous versions from explorer
  - !registryKey: {path: 'HKCR\AllFilesystemObjects\shellex\PropertySheetHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}'}
  - !registryKey: {path: 'HKCR\CLSID\{450D8FBA-AD25-11D0-98A8-0800361B1103}\shellex\PropertySheetHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}'}
  - !registryKey: {path: 'HKCR\Directory\shellex\PropertySheetHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}'}
  - !registryKey: {path: 'HKCR\Drive\shellex\PropertySheetHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}'}
  - !registryKey: {path: 'HKCR\AllFilesystemObjects\shellex\ContextMenuHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}'}
  - !registryKey: {path: 'HKCR\CLSID\{450D8FBA-AD25-11D0-98A8-0800361B1103}\shellex\ContextMenuHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}'}
  - !registryKey: {path: 'HKCR\Directory\shellex\ContextMenuHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}'}
  - !registryKey: {path: 'HKCR\Drive\shellex\ContextMenuHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer', value: 'NoPreviousVersionsPage', operation: delete}
  - !registryValue: {path: 'HKCU\SOFTWARE\Policies\Microsoft\PreviousVersions', value: 'DisableLocalPage', operation: delete}

  # - Remove cast to device
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked'
    value: '{7AD84985-87B4-4a16-BE58-8B72A5B390F7}'
    data: ''
    type: REG_SZ

  # - Remove Give access to
  - !registryKey: {path: 'HKCR\*\shellex\ContextMenuHandlers\Sharing'}
  - !registryKey: {path: 'HKCR\Directory\Background\shellex\ContextMenuHandlers\Sharing'}
  - !registryKey: {path: 'HKCR\Directory\shellex\ContextMenuHandlers\Sharing'}
  - !registryKey: {path: 'HKCR\Drive\shellex\ContextMenuHandlers\Sharing'}
  - !registryKey: {path: 'HKCR\LibraryFolder\background\shellex\ContextMenuHandlers\Sharing'}
  - !registryKey: {path: 'HKCR\UserLibraryFolder\shellex\ContextMenuHandlers\Sharing'}

  # - Remove inclucde in library
  - !registryKey: {path: 'HKCR\Folder\ShellEx\ContextMenuHandlers\Library Location'}

  # - Remove Bitmap
  - !registryKey: {path: 'HKCR\.bmp\ShellNew'}

  # - Remove Share
  - !registryKey: {path: 'HKCR\*\shellex\ContextMenuHandlers\ModernSharing'}
  - !registryKey: {path: 'HKCR\AllFilesystemObjects\shellex\ContextMenuHandlers\ModernSharing'}