---
title: configure-win32prioritysepartion
description: configure win32prioritysepartion
privilege: TrustedInstaller
actions:

  - !registryValue: {path: 'HKLM\SYSTEM\ControlSet001\Control\PriorityControl', value: 'Win32PrioritySeparation', type: REG_DWORD, data: '38'}